antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'cloud-aws'
    - '@springio/antora-extensions/static-page-extension'
site:
  title: Spring Cloud AWS
  url: https://awspring.io/spring-cloud-aws/docs/
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: docs
      worktrees: true
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-cloud-aws
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
    kroki-fetch-diagram: true
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - 'asciidoctor-kroki'
  sourcemap: true
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/maciejwalkowiak/antora-ui-spring-cloud-aws/raw/main/build/ui-bundle.zip
#    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.2/ui-bundle.zip
    snapshot: true
