name: Release

on:
  push:
    branches: [ 3.4.x-deploy ]
    tags:
      - v2.3.*
      - v2.4.*
      - v3.0.*
      - v3.1.*
      - v3.2.*
      - v3.3.*
      - v3.4.*

env:
  # https://github.com/actions/checkout/issues/440#issuecomment-854240996
  AWS_EC2_METADATA_DISABLED: true

permissions:
  contents: read

jobs:
  build:
    name: Release
    strategy:
      matrix:
        version: [ 17.0.12 ]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.version }}
          cache: maven
          server-id: central
          server-username: CENTRAL_TOKEN_USERNAME
          server-password: CENTRAL_TOKEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Run tests
        run: ./mvnw -V verify javadoc:aggregate -Pspring,docs-classic -DskipTests
      - name: Deploy to Sonatype
        run: ./mvnw -V -Prelease,spring deploy -DskipTests
        env:
          CENTRAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
